name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: workflow-application-token-action
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v2.1.0
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

      - name: Release
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
        run: npx semantic-release
